var fs=require("fs");
var d="/Users/daddy/work/ardudeck/apps/desktop/src/main/msp/";
var NL=String.fromCharCode(10);
var src=fs.readFileSync(d+"msp-handlers.ts","utf8").split(NL);
var code=src.slice(1193,1670).join(NL);
code=code.replaceAll("currentTransport","ctx.currentTransport");
code=code.replaceAll("isInavFirmware","ctx.isInavFirmware");
code=code.replaceAll("cachedInavPid","ctx.cachedInavPid");
code=code.replaceAll("currentPlatformType","ctx.currentPlatformType");
code=code.replaceAll("tuningCliModeActive","ctx.tuningCliModeActive");
code=code.replaceAll("tuningCliResponse","ctx.tuningCliResponse");
code=code.replaceAll("tuningCliListener","ctx.tuningCliListener");
code=code.replaceAll("pendingResponses","ctx.pendingResponses");
code=code.replaceAll("servoCliModeActive","ctx.servoCliModeActive");
code=code.replaceAll("sendLog(","ctx.sendLog(");
code=code.replaceAll("isLegacyInav()","ctx.isLegacyInav()");
code=code.replaceAll("usesMsp2Pid()","ctx.usesMsp2Pid()");
code=code.replaceAll("ctx.ctx.","ctx.");
code=code.replace(/^async function /gm,"export async function ");
var i=["import {"];
i.push("  MSP,","  MSP2,","  deserializePid,","  serializePid,");
i.push("  deserializeRcTuning,","  deserializeRcTuningInav,","  serializeRcTuning,","  serializeRcTuningInav,");
i.push("  deserializeInavRateProfile,","  serializeInavRateProfile,","  rcTuningToInavRateProfile,","  inavRateProfileToRcTuning,");
i.push("  deserializeInavPid,","  serializeInavPid,","  inavPidToPid,","  pidToInavPid,","  mergeInavPid,");
i.push("  type MSPPid,","  type MSPRcTuning,");
i.push("} from " + String.fromCharCode(39) + "@ardudeck/msp-ts" + String.fromCharCode(39) + ";");
var q=String.fromCharCode(39);
i.push("import { ctx } from "+q+"./msp-context.js"+q+";");
i.push("import {","  sendMspRequest,","  sendMspRequestWithPayload,","  sendMspV2Request,","  sendMspV2RequestWithPayload,","  withConfigLock,","  isCliModeBlockedError,");
i.push("} from "+q+"./msp-transport.js"+q+";");
i.push("import { startMspTelemetry, stopMspTelemetry } from "+q+"./msp-telemetry.js"+q+";");
var imp=i.join(NL)+NL+NL;
fs.writeFileSync(d+"msp-pid-rates.ts",imp+code+NL);
console.log("Written",fs.statSync(d+"msp-pid-rates.ts").size,"bytes");
