/**
 * Message Registry Generator
 * Generates the message info registry for runtime lookup
 */

import type { MavlinkMessage } from '../parsers/xml-parser.js';
import { calculateCrcExtra, getMessageSize } from '../parsers/xml-parser.js';

/**
 * Convert message name to TypeScript interface name
 */
function toInterfaceName(name: string): string {
  return name
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
}

/**
 * Generate the message registry TypeScript code
 */
export function generateRegistry(messages: MavlinkMessage[]): string {
  const lines: string[] = [];

  // Imports
  lines.push("import type { MessageInfo } from '@ardudeck/mavlink-ts';");
  lines.push('');

  // Import all message serializers/deserializers
  for (const msg of messages) {
    const fileName = msg.name.toLowerCase().replace(/_/g, '-');
    const interfaceName = toInterfaceName(msg.name);
    lines.push(
      `import { serialize${interfaceName}, deserialize${interfaceName} } from './messages/${fileName}.js';`
    );
  }
  lines.push('');

  // Generate registry entries
  lines.push('/**');
  lines.push(' * Message info registry');
  lines.push(' * Maps message IDs to their metadata and serialization functions');
  lines.push(' */');
  lines.push('export const MESSAGE_REGISTRY: Map<number, MessageInfo> = new Map([');

  for (const msg of messages) {
    const interfaceName = toInterfaceName(msg.name);
    const crcExtra = calculateCrcExtra(msg);
    const minLength = getMessageSize(msg, false);
    const maxLength = getMessageSize(msg, true);

    lines.push(`  [${msg.id}, {`);
    lines.push(`    msgid: ${msg.id},`);
    lines.push(`    name: '${msg.name}',`);
    lines.push(`    crcExtra: ${crcExtra},`);
    lines.push(`    minLength: ${minLength},`);
    lines.push(`    maxLength: ${maxLength},`);
    lines.push(`    serialize: serialize${interfaceName} as (msg: unknown) => Uint8Array,`);
    lines.push(`    deserialize: deserialize${interfaceName} as (payload: Uint8Array) => unknown,`);
    lines.push(`  }],`);
  }

  lines.push(']);');
  lines.push('');

  // Helper functions
  lines.push('/**');
  lines.push(' * Get message info by ID');
  lines.push(' */');
  lines.push('export function getMessageInfo(msgid: number): MessageInfo | undefined {');
  lines.push('  return MESSAGE_REGISTRY.get(msgid);');
  lines.push('}');
  lines.push('');

  lines.push('/**');
  lines.push(' * Get message info by name');
  lines.push(' */');
  lines.push('export function getMessageInfoByName(name: string): MessageInfo | undefined {');
  lines.push('  for (const info of MESSAGE_REGISTRY.values()) {');
  lines.push('    if (info.name === name) {');
  lines.push('      return info;');
  lines.push('    }');
  lines.push('  }');
  lines.push('  return undefined;');
  lines.push('}');
  lines.push('');

  lines.push('/**');
  lines.push(' * Get all registered message IDs');
  lines.push(' */');
  lines.push('export function getMessageIds(): number[] {');
  lines.push('  return Array.from(MESSAGE_REGISTRY.keys());');
  lines.push('}');
  lines.push('');

  lines.push('/**');
  lines.push(' * Get all message infos as an array');
  lines.push(' */');
  lines.push('export function getAllMessageInfos(): MessageInfo[] {');
  lines.push('  return Array.from(MESSAGE_REGISTRY.values());');
  lines.push('}');

  return lines.join('\n');
}

/**
 * Generate the main generated index file
 */
export function generateMainIndex(hasEnums: boolean, hasMessages: boolean): string {
  const lines: string[] = [];

  lines.push('/**');
  lines.push(' * Auto-generated MAVLink types');
  lines.push(' * DO NOT EDIT - Generated by @ardudeck/mavlink-generator');
  lines.push(' */');
  lines.push('');

  if (hasEnums) {
    lines.push("export * from './enums/index.js';");
  }

  if (hasMessages) {
    lines.push("export * from './messages/index.js';");
    lines.push("export * from './message-registry.js';");
  }

  return lines.join('\n');
}
