import { resolve } from 'path';
import { defineConfig, externalizeDepsPlugin } from 'electron-vite';
import react from '@vitejs/plugin-react';

// Production ships a strict CSP (script-src 'self', see renderer/index.html).
// In dev, @vitejs/plugin-react injects an inline React Fast Refresh preamble
// into index.html, which that policy would block — so relax script-src for the
// dev server only. The production build keeps the strict policy as written.
const cspDev = {
  name: 'csp-dev-relax',
  apply: 'serve' as const,
  transformIndexHtml(html: string) {
    return html.replace("script-src 'self'", "script-src 'self' 'unsafe-inline'");
  },
};

// electron-store must be bundled: it depends on conf -> env-paths@3 + 10 other
// ESM-only transitive deps that fail with ERR_MODULE_NOT_FOUND in packaged apps.
// Everything else (workspace packages, native modules) is handled correctly by
// externalizeDepsPlugin + electron-builder.
//
// Device Security & Licensing: the Ed25519 public key is injected at BUILD TIME
// (JAWJI_LICENSE_PUBLIC_KEY, generated by tools/license-keys.mjs). It is compiled
// into the main-process bundle so entitlement tokens can be verified fully
// offline; the private signing key never exists in any client.
const licensePublicKey = process.env.JAWJI_LICENSE_PUBLIC_KEY ?? '';

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin({ exclude: ['electron-store', '@jawji/dataflash-parser', '@jawji/module-sdk'] })],
    define: {
      __JAWJI_LICENSE_PUBLIC_KEY__: JSON.stringify(licensePublicKey),
    },
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/main/index.ts'),
        },
      },
    },
  },
  preload: {
    plugins: [externalizeDepsPlugin({ exclude: ['electron-store', '@jawji/module-sdk'] })],
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/main/preload.ts'),
        },
      },
    },
  },
  renderer: {
    root: 'src/renderer',
    build: {
      target: 'esnext',
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/renderer/index.html'),
        },
      },
    },
    optimizeDeps: {
      esbuildOptions: {
        target: 'esnext',
      },
    },
    plugins: [react(), cspDev],
  },
});
